### PR TITLE
Implement Pacifica Dispatcher

### LINKED ISSUE #6: Make Dispatcher do something real
### Pacifica Dispatcher version
Master
### Pacifica Core Software versions
Master
### Platform Details
Any
### Scenario:
It should actually receive cloud events and process an example based on that cloud event.

### PR DESCRIPTION
**Pull request by markborkum**
### Description

This pull request adds an implementation of the Pacifica Dispatcher service.

### Issues Resolved

#6 

### Check List

- [x] All tests pass. See <https://github.com/pacifica/pacifica-docs/blob/master/development/TESTING.md>
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by markborkum** [comment]
@dmlb2000 Over to you. Outstanding tasks:
* [ ] Spawn RabbitMQ before running test suite.
* [x] Resolve linter warnings.
* [ ] Add tests for remote downloader and uploader runners (this will necessitate using Docker to start other Pacifica services).
* [x] Create new "pacifica-dispatcher-example" repository for example usage of Pacifica Dispatcher service.

**Comment by dmlb2000** [comment]
@markborkum I was wondering about the example service, should that be a separate repository from this one or would simply putting the code in the `tests` directory be enough?

**Comment by markborkum** [comment]
@dmlb2000 If the example is separate, then its repository can be cloned (the base for other services).

**Comment by dmlb2000** [comment]
@markborkum I've got a repo created, but not setup yet, go ahead and make a pull to that while I work on this pull request. https://github.com/pacifica/pacifica-dispatcher-example.git

**Comment by markborkum** [comment]
@dmlb2000 Roger that. Please start with `.travis.yml`, `appveyor.yml` and `tests/receiver_test.py` (requirements: start RabbitMQ, start Celery, run test cases, delete "test.sqlite3" file).

**Comment by dmlb2000** [comment]
@markborkum I'm getting the same error in both Appveyor and Travis, your thoughts?

**Comment by dmlb2000** [comment]
@markborkum feels like something is a little racy with the test suite... keeps failing in slightly different places...

**Comment by markborkum** [comment]
@dmlb2000 The Appveyor error message for the `rm test.sqlite3` command is because, previously, the test suite created (and then deleted) a temporary file for the database, whereas now, it uses Postgres. More concerning is the regression in `router_test.py`.

**Comment by markborkum** [comment]
@dmlb2000 Fixed the regression. The commit message has instructions for local testing.

**Comment by dmlb2000** [comment]
@markborkum Okay I see what I did, thanks.

**Comment by markborkum** [comment]
@dmlb2000 Is there a Python idiom for returning when a generator (or list-like) yields any value? The `list` built-in forces the entire list into memory, which defeats the point of using generators.

**Comment by dmlb2000** [comment]
@markborkum I was looking for that as well, couldn't find it. Doing a `len(iter)` doesn't force things into memory but violates pylint iirc.

**Comment by dmlb2000** [comment]
@markborkum Yeah travis is still coming back with the receivetaskmodel not existing as a table. It feels like a race condition of some kind...

**Comment by markborkum** [comment]
@dmlb2000 Must be a PostgreSQL thing (it isn't raised when SQLite is used). I've added a line to create the database tables before calling the test methods.

**Comment by dmlb2000** [comment]
@markborkum Yeah, sometimes different databases have different behaviors with PeeWee. It's often the case when running long running services (like the wsgi or celery processes) to drop active connections to the database and reconnect when you receive a celery task or new wsgi request.

Here's the docs for MySQL at least.
http://docs.peewee-orm.com/en/latest/peewee/database.html#error-2006-mysql-server-has-gone-away

**Comment by markborkum** [comment]
@dmlb2000 In `.travis.yml#L71`, should the database connection URL have a password?

**Comment by dmlb2000** [comment]
@markborkum Yup, travis does no password for access to their database...

**Comment by markborkum** [comment]
@dmlb2000 This may not be a PostgreSQL issue. I just ran against a local PostgreSQL server and database. All tests passed.

Edit: This comment applies to stale code. Commit https://github.com/pacifica/pacifica-dispatcher/pull/7/commits/861d97faf3715cbdf3a9e55a167f04e93f3063ea introduces a regression here.

**Comment by dmlb2000** [comment]
@markborkum I got the test suite to pass, now it's just a matter of coverage.

**Comment by dmlb2000** [comment]
@markborkum So posix tar format requires unix style path separators, just FYI.

**Review by dmlb2000 — COMMENTED** [review]
This is ready to go.

**Review by dmlb2000 — APPROVED** [review]

**Pull request merged**
